CREATE DATABASE S3LAB2;
-------------------------------------------------------------------------------
CREATE TABLE EMPLOYEE(
EID INT,
ENAME VARCHAR(100),
GENDER VARCHAR(10),
JoiningDate datetime,
SALARY decimal(8,2),
CITY varchar(100));
----------------------------------------------------------------------------------------
INSERT INTO EMPLOYEE VALUES(1,'NICK','MALE','01-JAN-13',4000,'LONDON');
INSERT INTO EMPLOYEE VALUES(2,'JULIAN','FEMALE','01-OCT-14',3000,'NEW YORK');
INSERT INTO EMPLOYEE VALUES(3,'ROY','MALE','01-JUN-16',3500,'LONDON');
INSERT INTO EMPLOYEE VALUES(4,'TOM','MALE',NULL,4500,'LONDON');
INSERT INTO EMPLOYEE VALUES(5,'JERRY','MALE','01-FEB-13',2800,'SYDNEY');
INSERT INTO EMPLOYEE VALUES(6,'philip','MALE','01-JAN-15',7000,'NEW YORK');
INSERT INTO EMPLOYEE VALUES(7,'SARA','FEMALE','01-AUG-17',4800,'SYDNEY');
INSERT INTO EMPLOYEE VALUES(8,'EMILY','FEMALE','01-JAN-15',5500,'NEW YORK');
INSERT INTO EMPLOYEE VALUES(9,'MICHAEL','MALE',NULL,6500,'LONDON');
INSERT INTO EMPLOYEE VALUES(10,'JOHN','MALE','01-JAN-15',8800,'LONDON');
SELECT*FROM EMPLOYEE;
---------------------------------------------------------------------------------------
---Q.1
SELECT*FROM EMPLOYEE WHERE ENAME LIKE 'M%' AND ENAME LIKE '___H%';
--Q.2
SELECT POWER(3,5) as power_off;  
--Q.3
SELECT GETDATE()-20;
--Q.4
SELECT ENAME FROM EMPLOYEE WHERE ENAME LIKE 'J%' AND ENAME LIKE '%[n]%';
--Q.5
SELECT SUBSTRING('SQL PROGRAMING',2,9);
--Q.6
SELECT ENAME FROM EMPLOYEE WHERE CITY LIKE '%NEY'AND CITY LIKE '______';
--Q.7(i)
SELECT CONVERT(varchar,15);
--Q.7(ii)
select CAST(15 as varchar)as 'cast'
--Q.8
ALTER TABLE EMPLOYEE ADD DEPARTMENT VARCHAR(20);
SELECT * FROM EMPLOYEE;
--Q.9
UPDATE EMPLOYEE SET DEPARTMENT='MARKETING' WHERE CITY='LONDON';
--Q.10
SELECT*FROM EMPLOYEE WHERE ENAME LIKE '%[NY]';
--Q.11
SELECT CEILING(63.1),CEILING(63.8),CEILING(-63.2);
--Q.12
SELECT*FROM EMPLOYEE WHERE JoiningDate IS NULL;
--Q.13
SELECT UPPER(ENAME),LOWER(CITY) FROM EMPLOYEE;
--Q.14
ALTER TABLE EMPLOYEE ALTER COLUMN ENAME CHAR(30);
SELECT*FROM EMPLOYEE;
--Q.15
SELECT CITY,MAX(SALARY) FROM EMPLOYEE GROUP BY CITY;
--Q.16
--Q.17
SELECT COUNT(SALARY) FROM EMPLOYEE WHERE SALARY>5000;
--Q.18
Select LEFT ('EMPLOYEE',4), RIGHT ('EMPLOYEE',3);
--Q.19
--Q.20
--Q.21
SELECT CITY,AVG(SALARY)AS AVG_SALARY,COUNT(EID)AS TOTAL_EMPLOYYE_CITYWISE FROM EMPLOYEE GROUP BY(CITY);
--Q.22
SELECT SUM(SALARY)AS SUM_OF_ALL_FEMALE_SALARY FROM EMPLOYEE WHERE GENDER='FEMALE';
--Q.23
SELECT DATEDIFF(YEAR,GETDATE(),'JoiningDate') AS EXPERIENCE,ENAME FROM EMPLOYEE;
--Q.24
--ALTER TABLE EMPLOYEE DROP COLUMN DEPARTMENT;
--Q.25
--UPDATE EMPLOYEE SET CITY=NULL WHERE CITY='SYDNEY';
SELECT*FROM EMPLOYEE;
--Q.26
SELECT ENAME,SALARY,JOININGDATE FROM EMPLOYEE;
--Q.27
--Q.28
--Q.29
SP_RENAME'EMPLOYEE.', 'BDate', 'column'
--Q.30
SP_RENAME'EMPLOYEE','EMPMASTER';

