CREATE DATABASE WORKER_INFO_274;
--------------------------------------------------------------------------------------------
CREATE PROCEDURE PR_DEPARTMENT1_INSERT
    @DEPARTMENTID INT,
	@DEPARTMENTNAME VARCHAR(100)
AS 
BEGIN
INSERT INTO DEPARTMENT1
(
DEPARTMENTID,
DEPARTMENTNAME
)
VALUES
(
@DEPARTMENTID,
@DEPARTMENTNAME
)
END
EXEC PR_DEPARTMENT1_INSERT 1,ADMIN;
EXEC PR_DEPARTMENT1_INSERT 2,IT;
EXEC PR_DEPARTMENT1_INSERT 3,HR;
EXEC PR_DEPARTMENT1_INSERT 4,ACCOUNT;

SELECT*FROM DEPARTMENT1;

-----------------------------------------------------------------------------------------------------
CREATE PROCEDURE PR_DESIGNATION_INSERT
    @DESIGNATIONID INT,
	@DESIGNATIONNAME VARCHAR(100)
AS 
BEGIN
INSERT INTO DESIGNATION
(
DESIGNATIONID,
DESIGNATIONNAME
)
VALUES
(
@DESIGNATIONID,
@DESIGNATIONNAME
)
END

EXEC PR_DESIGNATION_INSERT 11,JOBBER;
EXEC PR_DESIGNATION_INSERT 12,WELDER;
EXEC PR_DESIGNATION_INSERT 13,CLERK;
EXEC PR_DESIGNATION_INSERT 14,MANAGER;
EXEC PR_DESIGNATION_INSERT 15,CEO;

SELECT*FROM DESIGNATION;

------------------------------------------------------------------------------------------------------------------------
CREATE PROCEDURE PR_PARSON_INSERT

	@FIRSTNAME VARCHAR(100),
	@LASTNAME VARCHAR(100),
	@SALARY DECIMAL(8,2),
	@JOININGDATE DATETIME,
	@DEPARMENTID INT,
	@DESIGNATIONID INT
AS 
BEGIN
INSERT INTO PARSON
(

	FIRSTNAME,
	LASTNAME,
	SALARY,
	JOININGDATE,
	departmentid,
	DESIGNATIONID
)
VALUES
(

	@FIRSTNAME,
	@LASTNAME,
	@SALARY,
	@JOININGDATE,
	@DEPARMENTID,
	@DESIGNATIONID
 )
END

EXEC PR_PARSON_INSERT 'RAHUL','ANSHU',56000,'01-01-1990',1,12;
EXEC PR_PARSON_INSERT  'HARDIK','HINSU',18000,'1990-09-25',2,11;
EXEC PR_PARSON_INSERT 'BHAVIN','KAMANI',25000,'1991-05-14',NULL,11;
EXEC PR_PARSON_INSERT 'BHOOMI','Patel',39000,'2014-02-20',1,13;
EXEC PR_PARSON_INSERT 'rohit','rajgor',17000,'1990-07-23',2,15;
EXEC PR_PARSON_INSERT 'priya','mehta',25000,'1990-10-18',2,null;
EXEC PR_PARSON_INSERT 'neha','trivedi',18000,'2014-02-20',3,15;

SELECT*FROM PARSON;

----------------------------------------------------------------------------------------------------------

CREATE PROCEDURE PR_DEPARTMENT1_UPDATE
    @DEPARTMENTID INT,
	@DEPARTMENTNAME VARCHAR(100)
AS 
UPDATE DEPARTMENT1
SET
         DEPARTMENTID=@DEPARTMENTID,
         DEPARTMENTNAME=@DEPARTMENTNAME
WHERE 
         DEPARTMENTID=@DEPARTMENTID

EXEC PR_DEPARTMENT1_UPDATE 1,ADMIN1

SELECT*FROM DEPARTMENT1;

--------------------------------------------------------------------------------------------------------------
CREATE PROCEDURE PR_DESIGNATION_UPDATE
    @DESIGNATIONID INT,
	@DESIGNATIONNAME VARCHAR(100)
AS 
UPDATE DESIGNATION
SET
         DESIGNATIONID=@DESIGNATIONID,
         DESIGNATIONNAME=@DESIGNATIONNAME
WHERE 
         DESIGNATIONID=@DESIGNATIONID

EXEC PR_DESIGNATION_UPDATE 11,JOBBER1

SELECT*FROM DESIGNATION;

-----------------------------------------------------------------------------------------------------------
CREATE PROCEDURE PR_PARSON_UPDATE
    @WORKERID INT,
    @FIRSTNAME VARCHAR(100),
	@LASTNAME VARCHAR(100),
	@SALARY DECIMAL(8,2),
	@JOININGDATE DATETIME,
	@DEPARTMENTID INT,
	@DESIGNATIONID INT
AS 
UPDATE PARSON
SET
    FIRSTNAME=@FIRSTNAME,
	LASTNAME=@LASTNAME,
	SALARY=@SALARY,
	JOININGDATE=@JOININGDATE,
	DEPARTMENTID=@DEPARTMENTID,
	DESIGNATIONID=@DESIGNATIONID        
WHERE 
         WORKERID=@WORKERID

EXEC PR_PARSON_UPDATE 
---------------------------------------------------------------




